# Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

"""Action-bundle interfaces for coordinated evidence generation."""

from evidenceforge.generation.actions.auth_session import (
    AnonymousLogonActionBundle,
    AnonymousLogonRequest,
    FailedLogonActionBundle,
    FailedLogonRequest,
    LogoffActionBundle,
    LogoffRequest,
    LogonActionBundle,
    LogonRequest,
    MachineAccountLogonActionBundle,
    MachineAccountLogonRequest,
    NtlmValidationActionBundle,
    NtlmValidationRequest,
    ServiceLogonActionBundle,
    ServiceLogonRequest,
    WorkstationLockActionBundle,
    WorkstationLockRequest,
    WorkstationLockResult,
    WorkstationUnlockActionBundle,
    WorkstationUnlockRequest,
)
from evidenceforge.generation.actions.base import ActionAnchor, ActionBundle
from evidenceforge.generation.actions.browser_session import (
    BrowserSessionActionBundle,
    BrowserSessionRequest,
    BrowserSessionResult,
)
from evidenceforge.generation.actions.command_effects import (
    CommandEffectIntent,
    EffectActorRef,
    EffectExecutionOutcome,
    EffectKind,
    EffectOutcomeStatus,
    EffectRequirement,
    ExecutionEffectAuditCounter,
    ExecutionEffectAuditSnapshot,
    ExecutionEffectNode,
    ExecutionEffectPlan,
    ExecutionEffectPlanError,
    ExecutionEffectPlanErrorCode,
    ExecutionEffectPlanSummary,
    ExecutionEffectReconciliation,
    ExecutionEffectResultSummary,
    ScannerEffectIntent,
    UnplannedEffectFailure,
)
from evidenceforge.generation.actions.dhcp_lease import (
    DhcpLeaseActionBundle,
    DhcpLeaseRequest,
    dhcp_renewal_interval_seconds,
    plan_dhcp_source_timeline,
)
from evidenceforge.generation.actions.dns_lookup import (
    DnsLookupActionBundle,
    DnsLookupRequest,
)
from evidenceforge.generation.actions.email import (
    EmailAccessActionBundle,
    EmailAccessRequest,
    EmailDeliveryActionBundle,
    EmailDeliveryRequest,
    EmailDeliveryResult,
)
from evidenceforge.generation.actions.file_transfer import (
    HttpFileTransferActionBundle,
    HttpFileTransferRequest,
    HttpFileTransferResult,
    HttpResponseFileTransferActionBundle,
    HttpResponseFileTransferRequest,
    HttpResponseFileTransferResult,
    ScpReceiverFileActionBundle,
    ScpReceiverFileRequest,
    StagedArchiveSmbReadActionBundle,
    StagedArchiveSmbReadRequest,
    file_transfer_hashes,
    http_response_parent_duration_floor,
    http_response_transfer_duration_floor,
)
from evidenceforge.generation.actions.ids_alert import (
    IdsAlertActionBundle,
    IdsAlertRequest,
    IdsAlertResult,
)
from evidenceforge.generation.actions.kerberos_dc import (
    KerberosConnectionAuditActionBundle,
    KerberosConnectionAuditRequest,
    KerberosLogonTicketsActionBundle,
    KerberosLogonTicketsRequest,
    KerberosPreauthFailureActionBundle,
    KerberosPreauthFailureRequest,
    KerberosServiceTicketActionBundle,
    KerberosServiceTicketRequest,
    KerberosTgtActionBundle,
    KerberosTgtRenewalActionBundle,
    KerberosTgtRenewalRequest,
    KerberosTgtRequest,
)
from evidenceforge.generation.actions.linux_shell_command import (
    LinuxShellCommandActionBundle,
    LinuxShellCommandRequest,
    plan_linux_pipeline_stage_times,
)
from evidenceforge.generation.actions.linux_sudo_session import (
    LinuxSudoSessionActionBundle,
    LinuxSudoSessionRequest,
    linux_sudo_intrinsic_close_headroom,
)
from evidenceforge.generation.actions.network_connection import (
    NetworkConnectionActionBundle,
    NetworkConnectionIdentityCapture,
    NetworkConnectionPublicationOutcome,
    NetworkConnectionRequest,
    PersistentSmbApplicationIntent,
    PersistentSmbRootHandoff,
    PersistentSmbRootIntent,
)
from evidenceforge.generation.actions.network_transaction_planner import (
    NetworkTransactionPlanner,
    dns_transport_close_headroom_seconds,
    http_completed_transport_close_bound_seconds,
    network_transport_open_positive_headroom_seconds,
    ntp_transport_close_headroom_seconds,
    tls_completed_extension_headroom_seconds,
    tls_completed_transport_close_bound_seconds,
    tls_generated_family_close_bound_seconds,
)
from evidenceforge.generation.actions.ocsp_transaction import (
    OcspTransactionActionBundle,
    OcspTransactionPlanner,
    OcspTransactionRequest,
)
from evidenceforge.generation.actions.process_execution import (
    ProcessExecutionActionBundle,
    ProcessExecutionPreparedEffects,
    ProcessExecutionRequest,
    ProcessRuntimeImageLoadPlan,
    ProcessTerminationActionBundle,
    ProcessTerminationRequest,
)
from evidenceforge.generation.actions.proxy_phase_planner import (
    proxy_transaction_close_bound_seconds,
)
from evidenceforge.generation.actions.proxy_transaction import (
    ProxyTransactionActionBundle,
    ProxyTransactionRequest,
)
from evidenceforge.generation.actions.rdp_session import (
    RdpSessionActionBundle,
    RdpSessionRequest,
    RdpSourceProcessFactory,
)
from evidenceforge.generation.actions.scanner_probe import (
    NmapCommandProbeActionBundle,
    NmapCommandProbePlan,
    NmapCommandProbePlanner,
    NmapCommandProbeRequest,
    NmapCommandProbeTarget,
    PortScanActionBundle,
    PortScanRequest,
    ScheduledScanOverlapActionBundle,
    ScheduledScanOverlapRequest,
    WebScanActionBundle,
    WebScanRequest,
    estimate_nmap_command_probe_occurrences,
)
from evidenceforge.generation.actions.smb_activity import (
    SmbActivityActionBundle,
    SmbActivityPreparation,
    SmbActivityRequest,
)
from evidenceforge.generation.actions.ssh_session import (
    SshSessionActionBundle,
    SshSessionRequest,
)
from evidenceforge.generation.actions.windows_audit import (
    AccountChangedActionBundle,
    AccountChangedRequest,
    AccountCreatedActionBundle,
    AccountCreatedRequest,
    AccountDeletedActionBundle,
    AccountDeletedRequest,
    CreateRemoteThreadActionBundle,
    CreateRemoteThreadRequest,
    GroupMembershipChangeActionBundle,
    GroupMembershipChangeRequest,
    LogClearedActionBundle,
    LogClearedRequest,
    PasswordChangeActionBundle,
    PasswordChangeRequest,
    PasswordResetActionBundle,
    PasswordResetRequest,
    ProcessAccessActionBundle,
    ProcessAccessRequest,
    ScheduledTaskActionBundle,
    ScheduledTaskRequest,
)
from evidenceforge.generation.actions.windows_remote_admin import (
    ExplicitCredentialUseActionBundle,
    ExplicitCredentialUseRequest,
    WindowsServiceInstallActionBundle,
    WindowsServiceInstallRequest,
)
from evidenceforge.generation.actions.windows_remote_authentication import (
    WindowsRemoteAuthenticationActionBundle,
    WindowsRemoteAuthenticationPlanner,
    WindowsRemoteAuthenticationRequest,
)
from evidenceforge.generation.persistent_smb_continuation import (
    PersistentSmbTerminalContinuation,
    PersistentSmbTerminalContinuationAuthority,
    PersistentSmbTerminalContinuationCensus,
    SmbActivityResult,
)

__all__ = [
    "AccountChangedActionBundle",
    "AccountChangedRequest",
    "AccountCreatedActionBundle",
    "AccountCreatedRequest",
    "AccountDeletedActionBundle",
    "AccountDeletedRequest",
    "ActionAnchor",
    "ActionBundle",
    "AnonymousLogonActionBundle",
    "AnonymousLogonRequest",
    "BrowserSessionActionBundle",
    "BrowserSessionRequest",
    "BrowserSessionResult",
    "CommandEffectIntent",
    "CreateRemoteThreadActionBundle",
    "CreateRemoteThreadRequest",
    "DhcpLeaseActionBundle",
    "DhcpLeaseRequest",
    "dhcp_renewal_interval_seconds",
    "plan_dhcp_source_timeline",
    "DnsLookupActionBundle",
    "DnsLookupRequest",
    "EmailAccessActionBundle",
    "EmailAccessRequest",
    "EmailDeliveryActionBundle",
    "EmailDeliveryRequest",
    "EmailDeliveryResult",
    "EffectActorRef",
    "EffectExecutionOutcome",
    "EffectKind",
    "EffectOutcomeStatus",
    "EffectRequirement",
    "ExecutionEffectAuditCounter",
    "ExecutionEffectAuditSnapshot",
    "ExecutionEffectNode",
    "ExecutionEffectPlan",
    "ExecutionEffectPlanError",
    "ExecutionEffectPlanErrorCode",
    "ExecutionEffectPlanSummary",
    "ExecutionEffectReconciliation",
    "ExecutionEffectResultSummary",
    "FailedLogonActionBundle",
    "FailedLogonRequest",
    "HttpResponseFileTransferActionBundle",
    "HttpResponseFileTransferRequest",
    "HttpResponseFileTransferResult",
    "HttpFileTransferActionBundle",
    "HttpFileTransferRequest",
    "HttpFileTransferResult",
    "http_response_parent_duration_floor",
    "http_response_transfer_duration_floor",
    "IdsAlertActionBundle",
    "IdsAlertRequest",
    "IdsAlertResult",
    "GroupMembershipChangeActionBundle",
    "GroupMembershipChangeRequest",
    "KerberosConnectionAuditActionBundle",
    "KerberosConnectionAuditRequest",
    "KerberosLogonTicketsActionBundle",
    "KerberosLogonTicketsRequest",
    "KerberosPreauthFailureActionBundle",
    "KerberosPreauthFailureRequest",
    "KerberosServiceTicketActionBundle",
    "KerberosServiceTicketRequest",
    "KerberosTgtActionBundle",
    "KerberosTgtRenewalActionBundle",
    "KerberosTgtRenewalRequest",
    "KerberosTgtRequest",
    "LogoffActionBundle",
    "LogoffRequest",
    "LogClearedActionBundle",
    "LogClearedRequest",
    "LogonActionBundle",
    "LogonRequest",
    "MachineAccountLogonActionBundle",
    "MachineAccountLogonRequest",
    "ScpReceiverFileActionBundle",
    "ScpReceiverFileRequest",
    "SmbActivityActionBundle",
    "SmbActivityPreparation",
    "SmbActivityRequest",
    "SmbActivityResult",
    "StagedArchiveSmbReadActionBundle",
    "StagedArchiveSmbReadRequest",
    "file_transfer_hashes",
    "LinuxShellCommandActionBundle",
    "LinuxShellCommandRequest",
    "plan_linux_pipeline_stage_times",
    "LinuxSudoSessionActionBundle",
    "LinuxSudoSessionRequest",
    "linux_sudo_intrinsic_close_headroom",
    "NetworkConnectionActionBundle",
    "NetworkConnectionIdentityCapture",
    "NetworkConnectionPublicationOutcome",
    "NetworkConnectionRequest",
    "PersistentSmbRootHandoff",
    "PersistentSmbApplicationIntent",
    "PersistentSmbRootIntent",
    "NetworkTransactionPlanner",
    "dns_transport_close_headroom_seconds",
    "http_completed_transport_close_bound_seconds",
    "network_transport_open_positive_headroom_seconds",
    "ntp_transport_close_headroom_seconds",
    "tls_completed_extension_headroom_seconds",
    "tls_completed_transport_close_bound_seconds",
    "tls_generated_family_close_bound_seconds",
    "NmapCommandProbeActionBundle",
    "NmapCommandProbeRequest",
    "NtlmValidationActionBundle",
    "NtlmValidationRequest",
    "OcspTransactionActionBundle",
    "OcspTransactionPlanner",
    "OcspTransactionRequest",
    "PasswordChangeActionBundle",
    "PasswordChangeRequest",
    "PasswordResetActionBundle",
    "PasswordResetRequest",
    "ProcessExecutionActionBundle",
    "ProcessExecutionPreparedEffects",
    "ProcessExecutionRequest",
    "ProcessAccessActionBundle",
    "ProcessAccessRequest",
    "ProcessRuntimeImageLoadPlan",
    "ProcessTerminationActionBundle",
    "ProcessTerminationRequest",
    "NmapCommandProbeActionBundle",
    "NmapCommandProbePlan",
    "NmapCommandProbePlanner",
    "NmapCommandProbeRequest",
    "NmapCommandProbeTarget",
    "estimate_nmap_command_probe_occurrences",
    "PortScanActionBundle",
    "PortScanRequest",
    "ProxyTransactionActionBundle",
    "ProxyTransactionRequest",
    "proxy_transaction_close_bound_seconds",
    "RdpSessionActionBundle",
    "RdpSessionRequest",
    "RdpSourceProcessFactory",
    "ScheduledScanOverlapActionBundle",
    "ScheduledScanOverlapRequest",
    "ScannerEffectIntent",
    "ScheduledTaskActionBundle",
    "ScheduledTaskRequest",
    "ServiceLogonActionBundle",
    "ServiceLogonRequest",
    "UnplannedEffectFailure",
    "WebScanActionBundle",
    "WebScanRequest",
    "SshSessionActionBundle",
    "SshSessionRequest",
    "ExplicitCredentialUseActionBundle",
    "ExplicitCredentialUseRequest",
    "WindowsServiceInstallActionBundle",
    "WindowsServiceInstallRequest",
    "WindowsRemoteAuthenticationActionBundle",
    "WindowsRemoteAuthenticationPlanner",
    "WindowsRemoteAuthenticationRequest",
    "WorkstationLockActionBundle",
    "WorkstationLockRequest",
    "WorkstationLockResult",
    "WorkstationUnlockActionBundle",
    "WorkstationUnlockRequest",
]
