# Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

"""Regression tests for bit-perfect generation repeatability."""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml
from typer.testing import CliRunner

from evidenceforge.cli.commands import app
from evidenceforge.composition import compile_scenario
from evidenceforge.composition.artifacts import RESOLVED_SCENARIO_FILENAME
from evidenceforge.events.observation_manifest import load_observation_manifest
from evidenceforge.generation.engine import GenerationEngine
from evidenceforge.generation.profiling import (
    GENERATION_PROFILE_FILENAME,
    GenerationProfileDocument,
    GenerationProfiler,
)
from evidenceforge.models.scenario import Scenario
from evidenceforge.utils.files import load_yaml


def _snapshot_generated_files(root: Path) -> dict[str, bytes]:
    """Return deterministic generated bytes, excluding timestamped run identity."""
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file() and path.name not in {"generation.log", "GENERATION_MANIFEST.json"}
    }


def test_opt_in_profiling_preserves_deterministic_bundle_bytes(tmp_path: Path) -> None:
    """Profiling may add one diagnostic sidecar but cannot alter generated evidence."""

    scenario_data = load_yaml(
        Path(__file__).parent.parent / "fixtures" / "scenarios" / "minimal.yaml"
    )
    scenario_data["time_window"]["warmup"] = "1h"
    scenario_data["baseline_activity"]["intensity"] = "low"
    scenario = Scenario(**scenario_data)
    unprofiled_root = tmp_path / "unprofiled"
    profiled_root = tmp_path / "profiled"

    GenerationEngine(
        scenario,
        unprofiled_root / "data",
        ground_truth_dir=unprofiled_root,
    ).generate()
    GenerationEngine(
        scenario,
        profiled_root / "data",
        ground_truth_dir=profiled_root,
        profiler=GenerationProfiler(
            scenario=scenario.name,
            generation_seed=scenario.generation_seed,
            output_target="default",
            selected_formats=tuple(log["format"] for log in scenario.output.logs),
            source_root=Path.cwd(),
        ),
    ).generate()

    assert (profiled_root / GENERATION_PROFILE_FILENAME).is_file()
    assert not (unprofiled_root / GENERATION_PROFILE_FILENAME).exists()
    profile_document = json.loads(
        (profiled_root / GENERATION_PROFILE_FILENAME).read_text(encoding="utf-8")
    )
    assert profile_document["emitters"]["windows_event_security"]["rendered_rows"] > 0
    assert profile_document["emitters"]["windows_event_sysmon"]["rendered_rows"] > 0
    assert profile_document["emitters"]["zeek_conn"]["rendered_rows"] > 0
    ignored = {"generation.log", "GENERATION_MANIFEST.json", GENERATION_PROFILE_FILENAME}
    unprofiled = {
        path.relative_to(unprofiled_root).as_posix(): path.read_bytes()
        for path in unprofiled_root.rglob("*")
        if path.is_file() and path.name not in ignored
    }
    profiled = {
        path.relative_to(profiled_root).as_posix(): path.read_bytes()
        for path in profiled_root.rglob("*")
        if path.is_file() and path.name not in ignored
    }
    assert profiled == unprofiled


def test_profile_metric_failure_degrades_report_without_failing_generation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Optional profile probes cannot compromise an otherwise valid bundle."""

    scenario_data = load_yaml(
        Path(__file__).parent.parent / "fixtures" / "scenarios" / "minimal.yaml"
    )
    scenario_data["time_window"]["warmup"] = "1h"
    scenario_data["baseline_activity"]["intensity"] = "low"
    scenario = Scenario(**scenario_data)
    bundle_root = tmp_path / "degraded-profile"
    profiler = GenerationProfiler(
        scenario=scenario.name,
        generation_seed=scenario.generation_seed,
        output_target="default",
        selected_formats=tuple(log["format"] for log in scenario.output.logs),
        source_root=Path.cwd(),
    )

    def fail_final_metrics(_snapshots: object) -> None:
        raise RuntimeError("injected metric-provider failure")

    monkeypatch.setattr(profiler, "record_final_emitters", fail_final_metrics)

    GenerationEngine(
        scenario,
        bundle_root / "data",
        ground_truth_dir=bundle_root,
        profiler=profiler,
    ).generate()

    profile_document = GenerationProfileDocument.model_validate_json(
        (bundle_root / GENERATION_PROFILE_FILENAME).read_text(encoding="utf-8")
    )
    assert profile_document.generation_status == "completed"
    assert profile_document.degraded
    expected_warnings = (
        "Unable to capture final emitter profile metrics: injected metric-provider failure",
    )
    if os.name == "nt":
        assert profile_document.sampler == "unavailable"
        expected_warnings = (
            "ITIMER_PROF sampling is unavailable; coarse metrics remain enabled",
            *expected_warnings,
        )
    assert profile_document.warnings == expected_warnings


def _linux_smb_scenario_path() -> Path:
    return Path(__file__).parent.parent / "fixtures" / "scenarios" / "smb-linux-matrix.yaml"


def _windows_smb_scenario_path() -> Path:
    return Path(__file__).parent.parent / "fixtures" / "scenarios" / "smb-resource-calibration.yaml"


class _LegacyProjectionEngine(GenerationEngine):
    """Test-only engine retaining the pre-deployment dispatcher projection path."""

    def _initialize(self) -> None:
        super()._initialize()
        self.dispatcher.collection_deployment = None


@pytest.mark.soak
def test_complete_profile_compiled_projection_preserves_legacy_bytes(tmp_path: Path) -> None:
    """Exact source fan-out must not alter a complete run without overrides."""

    scenario_path = Path(__file__).parent.parent / "fixtures" / "scenarios" / "minimal.yaml"
    scenario_data = load_yaml(scenario_path)
    scenario_data["output"]["logs"].extend(
        [
            {"format": "ecar"},
            {"format": "cisco_asa"},
        ]
    )
    compiled_dir = tmp_path / "compiled"
    legacy_dir = tmp_path / "legacy"

    GenerationEngine(Scenario(**scenario_data), compiled_dir).generate()
    _LegacyProjectionEngine(Scenario(**scenario_data), legacy_dir).generate()

    assert _snapshot_generated_files(compiled_dir) == _snapshot_generated_files(legacy_dir)


@pytest.mark.slow
def test_authoritative_eval_uses_project_observation_config(tmp_path: Path) -> None:
    """Bundle config must bind exact deployment matching through causality scoring."""

    project_root = tmp_path / "project"
    overlay_dir = project_root / ".eforge" / "config" / "activity"
    overlay_dir.mkdir(parents=True)
    (overlay_dir / "observation_profiles.yaml").write_text(
        yaml.safe_dump(
            {
                "schema_version": 2,
                "profiles": {
                    "complete": {
                        "sources": {"windows_security": {"missingness": 1.0}},
                    }
                },
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    scenario_data = load_yaml(
        Path(__file__).parent.parent / "fixtures" / "scenarios" / "minimal.yaml"
    )
    scenario_data["baseline_activity"]["intensity"] = "low"
    scenario_data["output"]["logs"] = [{"format": "windows_event_security"}]
    scenario_data["environment"]["observation_overrides"] = [
        {
            "source_instance": "windows_security:test-01",
            "enabled": True,
        }
    ]
    scenario_data["storyline"] = [
        {
            "id": "step-001",
            "time": "+10m",
            "actor": "test_user",
            "system": "TEST-01",
            "activity": "Run Calculator",
            "events": [
                {
                    "type": "process",
                    "process_name": "calc.exe",
                    "command_line": "calc.exe",
                }
            ],
        }
    ]
    scenario_path = project_root / "scenario.yaml"
    scenario_path.write_text(yaml.safe_dump(scenario_data, sort_keys=False), encoding="utf-8")
    compiled = compile_scenario(scenario_path, project_root=project_root)
    bundle = tmp_path / "bundle"
    data_dir = bundle / "data"

    GenerationEngine(
        compiled.scenario,
        data_dir,
        ground_truth_dir=bundle,
        scenario_root=project_root,
        compiled_scenario=compiled,
    ).generate()

    authoritative = compile_scenario(bundle / RESOLVED_SCENARIO_FILENAME)
    assert load_observation_manifest(data_dir, authoritative.scenario) is None
    assert (
        load_observation_manifest(
            data_dir,
            authoritative.scenario,
            effective_config=authoritative.effective_config,
        )
        is not None
    )

    result = CliRunner().invoke(app, ["eval", str(bundle), "--format", "json"])

    assert result.exit_code == 0, result.stdout
    report = json.loads(result.stdout)
    assert report["supplementary"]["observation_profile"]["manifest_present"] is True
    causality = next(pillar for pillar in report["pillars"] if pillar["name"] == "Causality")
    event_presence = next(
        score for score in causality["sub_scores"] if score["key"] == "event_presence"
    )
    assert event_presence["adjusted"] is True
    assert event_presence["score"] == 100.0


@pytest.mark.slow
def test_public_seed_is_repeatable_and_changes_generated_evidence(tmp_path: Path) -> None:
    """One public seed controls deterministic substreams without hiding a global singleton."""
    scenario_path = Path(__file__).parent.parent / "fixtures" / "scenarios" / "minimal.yaml"
    scenario_data = load_yaml(scenario_path)
    first_dir = tmp_path / "seed-7-first"
    second_dir = tmp_path / "seed-7-second"
    other_dir = tmp_path / "seed-8"

    GenerationEngine(Scenario(**scenario_data), first_dir, generation_seed=7).generate()
    GenerationEngine(Scenario(**scenario_data), second_dir, generation_seed=7).generate()
    GenerationEngine(Scenario(**scenario_data), other_dir, generation_seed=8).generate()

    first = _snapshot_generated_files(first_dir)
    assert first == _snapshot_generated_files(second_dir)
    assert first != _snapshot_generated_files(other_dir)


@pytest.mark.soak
def test_windows_smb_generation_is_bit_perfect_for_identical_inputs(tmp_path: Path) -> None:
    """Linux SMB planning must not perturb the established Windows-only RNG path."""

    scenario_data = load_yaml(_windows_smb_scenario_path())
    first_dir = tmp_path / "windows-smb-first"
    second_dir = tmp_path / "windows-smb-second"

    GenerationEngine(Scenario(**scenario_data), first_dir).generate()
    GenerationEngine(Scenario(**scenario_data), second_dir).generate()

    assert _snapshot_generated_files(first_dir) == _snapshot_generated_files(second_dir)


def test_prior_generation_in_same_process_does_not_change_output(tmp_path: Path) -> None:
    """Scenario-registered state (e.g. host reverse DNS) must not leak between runs."""
    fixtures = Path(__file__).parent.parent / "fixtures" / "scenarios"
    demo_path = Path(__file__).parent.parent.parent / "scenarios" / "macos-eslogger-demo"
    demo = load_yaml(demo_path / "scenario.yaml")

    GenerationEngine(Scenario(**demo), tmp_path / "clean").generate()
    GenerationEngine(
        Scenario(**load_yaml(fixtures / "minimal.yaml")), tmp_path / "other"
    ).generate()
    GenerationEngine(Scenario(**demo), tmp_path / "after").generate()

    assert _snapshot_generated_files(tmp_path / "clean") == _snapshot_generated_files(
        tmp_path / "after"
    )


@pytest.mark.soak
def test_common_outputs_and_ground_truth_ignore_format_filter(tmp_path: Path) -> None:
    """Selecting fewer renderers must not change canonical planning or shared bytes."""

    scenario_path = Path(__file__).parent.parent / "fixtures" / "scenarios" / "minimal.yaml"
    scenario_data = load_yaml(scenario_path)
    full_scenario = Scenario(**scenario_data)
    filtered_scenario = full_scenario.model_copy(deep=True)
    filtered_scenario.output.logs = [{"format": "zeek"}]
    full_dir = tmp_path / "full"
    filtered_dir = tmp_path / "filtered"

    GenerationEngine(full_scenario, full_dir).generate()
    GenerationEngine(filtered_scenario, filtered_dir).generate()

    filtered_data = {
        str(path.relative_to(filtered_dir)): path.read_bytes()
        for path in sorted(filtered_dir.rglob("*"))
        if path.is_file() and "core-zeek" in path.relative_to(filtered_dir).parts
    }
    assert filtered_data
    assert any(relative.startswith("core-zeek/") for relative in filtered_data)
    full_common_data = {relative: (full_dir / relative).read_bytes() for relative in filtered_data}
    assert full_common_data == filtered_data
    assert (full_dir / "GROUND_TRUTH.json").read_bytes() == (
        filtered_dir / "GROUND_TRUTH.json"
    ).read_bytes()


@pytest.mark.soak
def test_linux_smb_generation_ignores_python_hash_seed(tmp_path: Path) -> None:
    """Cross-platform SMB identities and artifacts must not depend on Python hash order."""

    scenario_path = _linux_smb_scenario_path()
    script = """
import sys
from pathlib import Path

from evidenceforge.generation.engine import GenerationEngine
from evidenceforge.models.scenario import Scenario
from evidenceforge.utils.files import load_yaml

scenario_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
GenerationEngine(Scenario(**load_yaml(scenario_path)), output_path).generate()
"""
    outputs = [tmp_path / "hash-seed-1", tmp_path / "hash-seed-99991"]
    for seed, output in zip(("1", "99991"), outputs, strict=True):
        result = subprocess.run(
            [sys.executable, "-c", script, str(scenario_path), str(output)],
            cwd=Path(__file__).parents[2],
            env={**os.environ, "PYTHONHASHSEED": seed},
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
        assert result.returncode == 0, result.stderr or result.stdout

    assert _snapshot_generated_files(outputs[0]) == _snapshot_generated_files(outputs[1])


@pytest.mark.slow
def test_storage_manifest_audience_ignores_python_hash_seed(tmp_path: Path) -> None:
    """Defensive manifest ordering must total-order casefold-equivalent set values."""

    script = """
import sys
from pathlib import Path

from evidenceforge.generation.storage_world import (
    CompiledStorageMapping,
    StorageWorldModel,
    write_storage_manifest,
)

world = StorageWorldModel(
    volumes=(),
    shares=(),
    mappings=(
        CompiledStorageMapping(
            id="defensive-order",
            share="FS-01.shared",
            users=frozenset({"alice", "Alice", "bob"}),
            systems=frozenset({"client-01", "CLIENT-01", "CLIENT-02"}),
            lifecycle="persistent",
        ),
    ),
)
write_storage_manifest(Path(sys.argv[1]), world)
"""
    outputs = [tmp_path / "manifest-seed-1.json", tmp_path / "manifest-seed-99991.json"]
    for seed, output in zip(("1", "99991"), outputs, strict=True):
        result = subprocess.run(
            [sys.executable, "-c", script, str(output)],
            cwd=Path(__file__).parents[2],
            env={**os.environ, "PYTHONHASHSEED": seed},
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        assert result.returncode == 0, result.stderr or result.stdout

    assert outputs[0].read_bytes() == outputs[1].read_bytes()
    mapping = json.loads(outputs[0].read_text(encoding="utf-8"))["mappings"][0]
    assert mapping["audience"] == {
        "systems": ["CLIENT-01", "client-01", "CLIENT-02"],
        "users": ["Alice", "alice", "bob"],
    }


@pytest.mark.soak
def test_linux_smb_common_outputs_ignore_format_filter(tmp_path: Path) -> None:
    """Linux/Samba canonical planning must be independent of selected renderers."""

    scenario_data = load_yaml(_linux_smb_scenario_path())
    full_scenario = Scenario(**scenario_data)
    filtered_scenario = full_scenario.model_copy(deep=True)
    filtered_scenario.output.logs = [{"format": "zeek"}, {"format": "syslog"}]
    full_dir = tmp_path / "linux-smb-full"
    filtered_dir = tmp_path / "linux-smb-filtered"

    GenerationEngine(full_scenario, full_dir).generate()
    GenerationEngine(filtered_scenario, filtered_dir).generate()

    filtered_data = {
        str(path.relative_to(filtered_dir)): path.read_bytes()
        for path in sorted(filtered_dir.rglob("*"))
        if path.is_file()
        and ("core-zeek" in path.relative_to(filtered_dir).parts or path.name == "syslog.log")
    }
    assert filtered_data
    assert any(relative.startswith("core-zeek/") for relative in filtered_data)
    assert any(relative.endswith("/syslog.log") for relative in filtered_data)
    full_common_data = {relative: (full_dir / relative).read_bytes() for relative in filtered_data}
    assert full_common_data == filtered_data
    full_truth = json.loads((full_dir / "GROUND_TRUTH.json").read_text(encoding="utf-8"))
    filtered_truth = json.loads((filtered_dir / "GROUND_TRUTH.json").read_text(encoding="utf-8"))
    # Source availability correctly reflects the selected renderers; canonical
    # storyline identities, operations, paths, UIDs, and FUIDs must not.
    full_truth.pop("source_evidence_status", None)
    filtered_truth.pop("source_evidence_status", None)
    for document in (full_truth, filtered_truth):
        for event in document["events"]:
            event.get("attributes", {}).pop("source_status", None)
        for intent in document.get("intent_reconciliation", {}).get("intents", []):
            intent.pop("source_status", None)
    assert full_truth == filtered_truth
    assert (full_dir / "STORAGE_MANIFEST.json").read_bytes() == (
        filtered_dir / "STORAGE_MANIFEST.json"
    ).read_bytes()
